### ISSUE TITLE
Incorrect output filename

### ISSUE THREAD

**Issue by Sniper199999** [wp-blocks/squashify#5]
If the input filename is `filename.png`, the output filename is `fileneame.png.webp`

The desired output should have been: 'filename.webp'

Node version: v18.18.0

The solution I had was: 
`const distFileName = distPath.replace(/\.[^/.]+$/, '') + utils_1.getOutputExtension(compressOpt.compressor, extension);`

can you update the package?

**Comment by erikyo** [comment]
Thank you for bringing this up. Originally, the addition of the input extension to the output filename (e.g., filename.png.webp) was intentional. This was because in certain server configurations, like with Nginx, it's easier to append an extension rather than replacing it.

However, I understand that in a more general context, this behavior is not desired, and it should indeed produce output filenames like 'filename.webp'.

I'll add this issue to our list of tasks to fix. Thank you for your feedback!

**Comment by erikyo** [comment]
@Sniper199999 i've updated the module (v1.0.0) and now you should be able output the images as requested. If give a try, let me have some feedback
